import { useNavigate } from "react-router-dom";
import {
  ArrowUp,
  BookOpen,
  BrainCircuit,
  Check,
  CheckCircle2,
  CircleHelp,
  ClipboardCheck,
  Clock3,
  FileSearch,
  GraduationCap,
  Lightbulb,
  MessageSquare,
  PenLine,
  Presentation,
  ShieldCheck,
  Target,
  Timer,
  UserCheck,
  Users,
} from "lucide-react";
import { Mockup, type ScreenKey } from "./PBLGuide";
import "./pbl-guide.css";

type SectionTone = "blue" | "orange" | "green" | "dark";

function SectionHeading({ number, tone = "blue", eyebrow, title }: { number: string; tone?: SectionTone; eyebrow: string; title: string }) {
  return <div className="pbl-section-heading"><span className={`pbl-section-number ${tone}`}>{number}</span><div><div className="pbl-eyebrow">{eyebrow}</div><h2>{title}</h2></div></div>;
}

function Notice({ tone = "blue", icon, title, children }: { tone?: "blue" | "amber" | "green"; icon: string; title: string; children: React.ReactNode }) {
  return <div className={`pbl-notice pbl-notice-${tone}`}><span className="pbl-notice-icon" aria-hidden="true">{icon}</span><div><strong>{title}</strong><p>{children}</p></div></div>;
}

function StepList({ items }: { items: Array<{ title: string; text: string }> }) {
  return <div className="pbl-step-list">{items.map((item, index) => <div className="pbl-step-row" key={item.title}><span className="pbl-step-badge">{index + 1}</span><div><strong>{item.title}</strong><p>{item.text}</p></div></div>)}</div>;
}

function ScreenFigure({ screen, title, children, wide = false }: { screen: ScreenKey; title: string; children: React.ReactNode; wide?: boolean }) {
  return <figure className={`pbl-screen-figure ${wide ? "pbl-wide-figure" : ""}`}><div className="pbl-screen-wrap"><Mockup screen={screen} /></div><figcaption><b>{title}</b> {children}</figcaption></figure>;
}

export default function PBLGuideDetailed() {
  const navigate = useNavigate();
  const handleToolCardClick = (event: React.MouseEvent<HTMLDivElement>) => {
    const card = (event.target as HTMLElement).closest<HTMLElement>(".pbl-tool-card");
    const title = card?.querySelector("h3")?.textContent?.trim();
    const toolRoutes: Record<string, string> = {
      "Chat em tempo real": "chat",
      "Whiteboard colaborativo": "whiteboard",
      "Mapa conceitual": "mapa-conceitual",
      "Referências e busca científica": "referencias",
      "Timer da sessão": "timer",
      "AI Co-tutor e apoio": "ai-co-tutor",
    };
    const slug = title ? toolRoutes[title] : undefined;
    if (slug) navigate(`/como-funciona/ferramentas/${slug}`);
  };

  return <div className="pbl-doc" onClick={handleToolCardClick}>
    <a className="pbl-skip-link" href="#pbl-conteudo">Pular para o conteúdo</a>

    <header className="pbl-topbar">
      <div className="pbl-topbar-inner">
        <button className="pbl-brand" onClick={() => navigate("/")} aria-label="PBL Virtual — início"><span className="pbl-brand-mark"><GraduationCap className="h-4 w-4" /></span><span>PBL Virtual</span></button>
        <div className="pbl-topbar-actions"><span className="pbl-status-dot"><i aria-hidden="true" /> Guia de uso da plataforma</span><button className="pbl-home-button" onClick={() => navigate("/")}>Voltar à home</button><button className="pbl-print-button" onClick={() => window.print()}>Imprimir guia</button></div>
      </div>
    </header>

    <main id="pbl-conteudo">
      <section className="pbl-hero" id="inicio"><div className="pbl-hero-inner"><div className="pbl-eyebrow">Antes de entrar na sala tutorial</div><h1>Como usar o sistema PBL Virtual</h1><p className="pbl-hero-lead">Este guia explica, em linguagem direta e com as telas da plataforma, o que alunos e professores fazem antes, durante e depois de uma sessão PBL.</p><div className="pbl-hero-grid"><div className="pbl-hero-callout"><span className="pbl-callout-kicker">Em uma frase</span><strong>Você entra no caso, constrói o raciocínio com seu grupo e transforma a discussão em evidência de aprendizagem.</strong><span>O professor controla a passagem entre os passos; a tela de cada participante acompanha a sala em tempo real.</span></div><div className="pbl-hero-stats" aria-label="Resumo do guia"><div><b>7</b><span>passos da sessão tutorial</span></div><div><b>2</b><span>perfis: aluno e professor</span></div><div><b>1</b><span>sala para todo o processo</span></div></div></div></div></section>

      <div className="pbl-page-shell">
        <aside className="pbl-side-nav" aria-label="Navegação deste guia"><div className="pbl-side-nav-title">Neste guia</div><nav><a href="#comece">Comece por aqui</a><a href="#fluxo">1. Entender o fluxo</a><a href="#professor-prepara">2. Preparação do professor</a><a href="#aluno-acesso">3. Acesso do aluno</a><a href="#p1-p2">4. P1 e P2</a><a href="#p3-p4">5. P3 e P4</a><a href="#p5-p6">6. P5 e P6</a><a href="#p7">7. P7 e avaliação</a><a href="#ferramentas">8. Ferramentas da sala</a><a href="#professor-conduz">9. Condução do professor</a><a href="#relatorios">10. Relatórios</a><a href="#boas-praticas">Boas práticas</a><a href="#duvidas">Dúvidas comuns</a></nav><div className="pbl-side-tip"><span aria-hidden="true">⌁</span><p>Deixe este guia aberto em outra aba durante sua primeira sessão PBL.</p></div></aside>

        <div className="pbl-content-column">
          <section className="pbl-content-section" id="comece"><SectionHeading number="00" eyebrow="Preparação" title="Comece por aqui" /><div className="pbl-notice pbl-notice-blue"><span className="pbl-notice-icon">i</span><div><strong>O que você precisa ter em mãos</strong><p>O endereço do PBL Virtual, seu acesso à instituição, a turma ou sala indicada pelo professor e alguns minutos para conhecer o cenário antes do encontro.</p></div></div><div className="pbl-check-grid"><div className="pbl-check-item"><span>01</span><div><strong>Use um dispositivo com internet</strong><p>Celular, tablet ou computador. Prefira uma conexão estável e mantenha o navegador atualizado.</p></div></div><div className="pbl-check-item"><span>02</span><div><strong>Reserve toda a sessão</strong><p>O professor libera os passos em sequência. Não feche a sala enquanto estiver aguardando a próxima etapa.</p></div></div><div className="pbl-check-item"><span>03</span><div><strong>Entre com seu próprio acesso</strong><p>O histórico de chat, contribuições, referências e avaliações fica vinculado ao seu perfil.</p></div></div></div><Notice tone="amber" icon="!" title="Uma sessão PBL é mais do que responder certo">A plataforma registra também como o grupo chegou à resposta: hipóteses, objetivos, referências, apresentação, participação e avaliação.</Notice></section>

          <section className="pbl-content-section" id="fluxo"><SectionHeading number="01" tone="orange" eyebrow="Visão geral" title="Entender o fluxo da sessão tutorial" /><p>O PBL Virtual organiza a atividade em <strong>sete passos</strong>. O professor conduz o avanço; os alunos veem o mesmo momento, com as ferramentas adequadas para contribuir. É normal ver uma tela de espera entre dois passos: isso significa que a turma ainda está sendo preparada para a próxima conversa.</p><div className="pbl-flow-map" role="list" aria-label="Etapas da sessão PBL"><div className="pbl-flow-step pbl-flow-wait" role="listitem"><span>01</span><b>P1</b><small>Termos</small></div><i>→</i><div className="pbl-flow-step pbl-flow-blue" role="listitem"><span>02</span><b>P2</b><small>Problema</small></div><i>→</i><div className="pbl-flow-step pbl-flow-orange" role="listitem"><span>03</span><b>P3</b><small>Hipóteses</small></div><i>→</i><div className="pbl-flow-step pbl-flow-orange" role="listitem"><span>04</span><b>P4</b><small>Sistematização</small></div><i>→</i><div className="pbl-flow-step pbl-flow-green" role="listitem"><span>05</span><b>P5</b><small>Objetivos</small></div><i>→</i><div className="pbl-flow-step pbl-flow-green" role="listitem"><span>06</span><b>P6</b><small>Estudo</small></div><i>→</i><div className="pbl-flow-step pbl-flow-dark" role="listitem"><span>07</span><b>P7</b><small>Fechamento</small></div></div><div className="pbl-phase-table" role="table" aria-label="Resumo dos passos PBL"><div className="pbl-phase-row pbl-phase-header" role="row"><span role="columnheader">Passo</span><span role="columnheader">O que acontece</span><span role="columnheader">Quem conduz</span></div><div className="pbl-phase-row" role="row"><span role="cell"><b className="pbl-blue-dot" /> P1–P2</span><span role="cell">O grupo entende o cenário, esclarece termos e define o problema de forma consensuada.</span><span role="cell">Grupo + Relator</span></div><div className="pbl-phase-row" role="row"><span role="cell"><b className="pbl-orange-dot" /> P3–P4</span><span role="cell">As hipóteses são levantadas, discutidas e organizadas em conexões visíveis.</span><span role="cell">Grupo + Relator</span></div><div className="pbl-phase-row" role="row"><span role="cell"><b className="pbl-green-dot" /> P5–P6</span><span role="cell">O grupo define o que precisa aprender e estuda individualmente com referências.</span><span role="cell">Grupo + Professor</span></div><div className="pbl-phase-row" role="row"><span role="cell"><b className="pbl-blue-dot" /> P7</span><span role="cell">A equipe apresenta a síntese, conecta evidências e reflete sobre a participação.</span><span role="cell">Relator + Professor</span></div></div></section>

          <section className="pbl-content-section" id="professor-prepara"><SectionHeading number="02" tone="green" eyebrow="Antes do encontro · Professor" title="Preparar a sala e o cenário" /><p>O professor chega à sessão com a sala pronta para que a energia do encontro fique concentrada na mediação. Antes de liberar o caso, confira participantes, critérios de avaliação e papéis do grupo.</p><ScreenFigure screen="professor-dashboard" title="Tela 1.">No painel de salas, o professor acompanha turmas em andamento, próximas sessões, número de alunos e cenário vinculado.</ScreenFigure><StepList items={[{ title: "Abra a turma correta", text: "Acesse Salas no menu lateral e confira curso, módulo, grupo e horário antes de entrar." }, { title: "Vincule o cenário", text: "Em Gerenciar cenários, escolha o caso da sessão e revise se ele está associado ao módulo correto." }, { title: "Defina os papéis", text: "Escolha Coordenador e Relator no painel Participantes. Eles podem ser trocados durante o encontro." }, { title: "Confira critérios e timer", text: "Revise avaliação, duração da abertura e fechamento e os recursos que serão liberados para a turma." }]} /><Notice tone="green" icon="✓" title="Preparar não significa antecipar a resposta">Deixe o cenário e as regras claros, mas preserve o espaço para o grupo levantar hipóteses, negociar objetivos e justificar suas escolhas.</Notice></section>

          <section className="pbl-content-section" id="aluno-acesso"><SectionHeading number="03" eyebrow="Entrada · Aluno" title="Acessar a sala virtual" /><p>O aluno encontra a sessão no painel pessoal. Ao abrir a sala, a tela mostra o cenário que foi liberado, os colegas conectados e o passo em que o grupo está.</p><StepList items={[{ title: "Abra Meu painel", text: "Procure a sala indicada pelo professor. Confira o horário e a turma antes de entrar." }, { title: "Clique em Entrar na sala", text: "Aguarde a sincronização. Se o professor ainda não tiver liberado o caso, você verá a etapa de espera." }, { title: "Confira seu papel", text: "Veja se você é Coordenador, Relator ou Participante e entenda o que cada papel pode registrar." }]} /><ScreenFigure screen="student-dashboard" title="Tela 2.">O painel do aluno destaca a sessão de hoje, a etapa atual, a participação e o botão para entrar na sala.</ScreenFigure><Notice tone="amber" icon="!" title="Se a conexão cair">Não abra uma nova sala por conta própria. Volte ao mesmo painel, entre novamente na sala e confira se suas contribuições já foram sincronizadas.</Notice></section>

          <section className="pbl-content-section" id="p1-p2"><SectionHeading number="04" eyebrow="Abertura · P1 e P2" title="Ler o problema e definir o foco" /><div className="pbl-definition"><strong>P1 → P2</strong><span>Do vocabulário do caso à definição consensuada do problema.</span></div><p>Leia o cenário com atenção e use a primeira conversa para tornar o caso compreensível a todos. O objetivo não é encontrar uma resposta agora; é construir uma pergunta que organize a investigação do grupo.</p><div className="pbl-rules-grid"><div><b className="pbl-rule-icon">01</b><strong>Esclareça termos</strong><p>Registre palavras, expressões clínicas e informações que precisam ser compreendidas antes da discussão.</p></div><div><b className="pbl-rule-icon">02</b><strong>Separe fatos de perguntas</strong><p>Marque o que o caso já informa e o que o grupo ainda precisa descobrir ou explicar.</p></div><div><b className="pbl-rule-icon">03</b><strong>Defina um problema</strong><p>Escreva uma formulação curta, clara e compartilhada pelo grupo. Ela será o ponto de partida das hipóteses.</p></div></div><ScreenFigure screen="room-flow" title="Tela 3." wide>A sala mostra a etapa ativa no topo, o cenário liberado no centro e o chat para que o grupo registre a conversa.</ScreenFigure><Notice tone="blue" icon="i" title="O professor avança o passo">Se o P2 ainda não estiver liberado, use o tempo para ler, conversar e organizar os termos. A mudança de etapa aparece para todos ao mesmo tempo.</Notice></section>

          <section className="pbl-content-section" id="p3-p4"><SectionHeading number="05" tone="orange" eyebrow="Raciocínio coletivo · P3 e P4" title="Construir hipóteses e sistematizar" /><p>No brainstorming, todas as hipóteses são bem-vindas quando estão relacionadas ao caso. Depois, o grupo organiza as ideias, identifica conexões e decide o que merece ser investigado no estudo individual.</p><div className="pbl-timeline"><div className="pbl-timeline-item"><span>1</span><div><strong>Contribua com uma hipótese</strong><p>Explique de onde ela vem e qual informação do cenário a sustenta.</p></div></div><div className="pbl-timeline-item"><span>2</span><div><strong>Escute e conecte</strong><p>Compare ideias semelhantes, faça perguntas e registre relações no mapa conceitual.</p></div></div><div className="pbl-timeline-item"><span>3</span><div><strong>Organize no whiteboard</strong><p>O Relator transforma a conversa em termos, grupos e setas que todos conseguem revisar.</p></div></div><div className="pbl-timeline-item"><span>4</span><div><strong>Prepare a passagem para o P5</strong><p>Separe hipóteses que precisam de evidência e temas que podem virar objetivos de aprendizagem.</p></div></div></div><ScreenFigure screen="collaboration" title="Tela 4." wide>Chat, whiteboard e mapa conceitual ficam próximos para tornar o raciocínio do grupo visível.</ScreenFigure><div className="pbl-notice pbl-notice-amber"><span className="pbl-notice-icon">!</span><div><strong>O Relator registra; o grupo pensa junto</strong><p>Mesmo que apenas o Relator edite o quadro, todos devem sugerir, revisar e confirmar o que foi registrado.</p></div></div></section>

          <section className="pbl-content-section" id="p5-p6"><SectionHeading number="06" tone="green" eyebrow="Aprendizagem · P5 e P6" title="Transformar a discussão em objetivos e estudo" /><p>O P5 responde à pergunta: <strong>o que precisamos aprender para explicar este caso?</strong> Os objetivos aprovados orientam o estudo individual e aparecem novamente no fechamento.</p><div className="pbl-image-grid two-up"><ScreenFigure screen="objectives" title="Tela 5.">O Banco de Objetivos organiza propostas, objetivos aprovados e o que cada aluno está estudando.</ScreenFigure><ScreenFigure screen="research" title="Tela 6.">No P6, cada referência pode ser vinculada ao objetivo que ajuda a responder.</ScreenFigure></div><div className="pbl-step-list"><div className="pbl-step-row"><span className="pbl-step-badge">1</span><div><strong>Escreva objetivos investigáveis</strong><p>Use verbos de ação, como explicar, comparar, identificar, interpretar ou aplicar.</p></div></div><div className="pbl-step-row"><span className="pbl-step-badge">2</span><div><strong>Distribua responsabilidades</strong><p>O grupo pode dividir objetivos entre pessoas, mas o encontro de fechamento continua sendo coletivo.</p></div></div><div className="pbl-step-row"><span className="pbl-step-badge">3</span><div><strong>Anexe evidências</strong><p>Registre título, autoria, link ou DOI e uma nota breve explicando como a fonte ajuda.</p></div></div></div><Notice tone="green" icon="✓" title="Uma referência precisa responder a um objetivo">O objetivo não é acumular links. Escolha fontes que ajudem o grupo a explicar, comparar ou tomar uma decisão com base no caso.</Notice></section>

          <section className="pbl-content-section" id="p7"><SectionHeading number="07" tone="dark" eyebrow="Fechamento · P7" title="Apresentar, discutir e avaliar" /><p>O P7 é o momento de devolver ao grupo o que foi aprendido. O Relator conduz a apresentação, todos podem comentar os slides e o professor fecha a sessão com veredito e avaliação.</p><div className="pbl-image-grid two-up"><ScreenFigure screen="presentation" title="Tela 7.">A apresentação sincroniza o slide atual e permite comentar cada parte da síntese.</ScreenFigure><ScreenFigure screen="evaluation" title="Tela 8.">A avaliação registra participação, colaboração, argumentação e a reflexão individual.</ScreenFigure></div><div className="pbl-rules-grid"><div><b className="pbl-rule-icon">01</b><strong>Apresente a síntese</strong><p>Relacione conclusões aos objetivos e mostre as referências que sustentam cada ponto.</p></div><div><b className="pbl-rule-icon">02</b><strong>Comente com precisão</strong><p>Cite o slide, a evidência ou a lacuna. O comentário deve ajudar a melhorar o raciocínio.</p></div><div><b className="pbl-rule-icon">03</b><strong>Feche o ciclo</strong><p>Revise veredito, avaliação por pares e próximos passos antes de finalizar o P7.</p></div></div><Notice tone="blue" icon="i" title="O relatório reúne o processo">A sessão não termina apenas na nota: chat, objetivos, referências, comentários e avaliação formam a memória de aprendizagem do grupo.</Notice></section>

          <section className="pbl-content-section" id="ferramentas"><SectionHeading number="08" eyebrow="Dentro da sala" title="Conhecer as ferramentas da sala" /><p>As ferramentas ficam na própria sala para que o grupo não precise alternar entre vários aplicativos. Cada uma tem uma função: conversar, tornar o pensamento visível, buscar evidências ou acompanhar o tempo.</p><div className="pbl-tool-grid"><div className="pbl-tool-card"><span className="pbl-tool-icon"><MessageSquare className="h-4 w-4" /></span><div><h3>Chat em tempo real</h3><p>Converse com o grupo, marque colegas e mantenha o histórico das decisões da sessão.</p></div></div><div className="pbl-tool-card"><span className="pbl-tool-icon orange"><PenLine className="h-4 w-4" /></span><div><h3>Whiteboard colaborativo</h3><p>Registre termos, hipóteses e sínteses. O Relator organiza o quadro e o grupo revisa.</p></div></div><div className="pbl-tool-card"><span className="pbl-tool-icon green"><BrainCircuit className="h-4 w-4" /></span><div><h3>Mapa conceitual</h3><p>Conecte causas, mecanismos, sinais, hipóteses e objetivos de maneira visual.</p></div></div><div className="pbl-tool-card"><span className="pbl-tool-icon"><FileSearch className="h-4 w-4" /></span><div><h3>Referências e busca científica</h3><p>Pesquise artigos e anexe DOI, link ou PDF ao objetivo correspondente.</p></div></div><div className="pbl-tool-card"><span className="pbl-tool-icon orange"><Timer className="h-4 w-4" /></span><div><h3>Timer da sessão</h3><p>O tempo de abertura, fechamento e fala ajuda a turma a distribuir o encontro.</p></div></div><div className="pbl-tool-card"><span className="pbl-tool-icon green"><CircleHelp className="h-4 w-4" /></span><div><h3>AI Co-tutor e apoio</h3><p>Use perguntas-guia e apoio contextual quando o professor liberar o recurso para a sala.</p></div></div></div></section>

          <section className="pbl-content-section" id="professor-conduz"><SectionHeading number="09" tone="green" eyebrow="Mediação · Professor" title="Conduzir sem perder o grupo de vista" /><p>Durante a sessão, o professor acompanha o raciocínio e decide quando o grupo está pronto para avançar. O sistema oferece o ritmo, os indicadores e os registros para que a intervenção seja mais precisa.</p><ScreenFigure screen="control" title="Tela 9." wide>O controle da sessão mostra P1–P7, o timer, participantes conectados e o momento atual da turma.</ScreenFigure><div className="pbl-timeline"><div className="pbl-timeline-item"><span>1</span><div><strong>Observe antes de intervir</strong><p>Veja quem está participando, quais hipóteses apareceram e se a conversa está conectada ao caso.</p></div></div><div className="pbl-timeline-item"><span>2</span><div><strong>Use perguntas de mediação</strong><p>Peça evidências, comparação ou explicação. Evite substituir a investigação do grupo pela resposta do professor.</p></div></div><div className="pbl-timeline-item"><span>3</span><div><strong>Avance quando houver síntese</strong><p>O passo seguinte deve ser uma consequência do que o grupo construiu, não apenas do relógio.</p></div></div><div className="pbl-timeline-item"><span>4</span><div><strong>Registre o que merece acompanhamento</strong><p>Use observações, avaliação e relatório para planejar a próxima sessão ou uma intervenção individual.</p></div></div></div><ScreenFigure screen="monitor" title="Tela 10.">O acompanhamento destaca participação, papéis e lacunas de objetivos sem interromper a conversa do grupo.</ScreenFigure></section>

          <section className="pbl-content-section" id="relatorios"><SectionHeading number="10" eyebrow="Depois da sessão" title="Finalizar, avaliar e consultar relatórios" /><p>Antes de concluir o P7, revise se a apresentação foi enviada, se os objetivos têm referências e se as avaliações estão preenchidas. Depois, o sistema gera uma ata e organiza indicadores para a turma.</p><ScreenFigure screen="finalize" title="Tela 11." wide>O checklist de fechamento ajuda o professor a concluir o P7 com veredito, referências e avaliações completas.</ScreenFigure><div className="pbl-weight-cards"><div className="pbl-weight-card pbl-blue-card"><span>Processo</span><strong>Chat</strong><small>contribuições e decisões registradas</small></div><div className="pbl-weight-card pbl-orange-card"><span>Aprendizagem</span><strong>Objetivos</strong><small>fontes e sínteses vinculadas ao caso</small></div><div className="pbl-weight-card pbl-green-card"><span>Reflexão</span><strong>Avaliação</strong><small>participação, colaboração e próximos passos</small></div></div><div className="pbl-formula-box"><div className="pbl-formula-title">O que o relatório conecta</div><div className="pbl-formula-row"><span>Participação</span><b>+</b><span>contribuições, tempo de fala e papéis assumidos</span></div><div className="pbl-formula-row"><span>Aprendizagem</span><b>+</b><span>objetivos, referências, apresentação e comentários</span></div><div className="pbl-formula-row pbl-formula-final"><span>Visão do tutor</span><b>=</b><span>evidências do processo + avaliação + próximos passos</span></div></div><Notice tone="green" icon="✓" title="Finalize somente quando a turma tiver encerrado">Depois de finalizar o P7, os registros ficam disponíveis para consulta e relatório. Faça uma última revisão antes de confirmar.</Notice></section>

          <section className="pbl-content-section" id="boas-praticas"><SectionHeading number="+" tone="dark" eyebrow="Participação" title="Como contribuir bem com sua equipe" /><div className="pbl-role-grid"><div className="pbl-role-card"><span className="pbl-role-icon"><GraduationCap className="h-4 w-4" /></span><h3>Para o aluno</h3><p>Explique o porquê, escute antes de fechar, use o erro como pista, cumpra seu objetivo de estudo e registre fontes que o grupo consiga retomar.</p></div><div className="pbl-role-card teacher"><span className="pbl-role-icon"><UserCheck className="h-4 w-4" /></span><h3>Para o professor</h3><p>Prepare o contexto, preserve o tempo de pensamento, faça perguntas de mediação, observe a participação e dê feedback sobre o processo.</p></div></div><div className="pbl-principles"><div><b>Uma boa hipótese é justificável.</b><span>Relacione sua ideia a um dado do cenário, mesmo que ela ainda precise ser revisada.</span></div><div><b>Um bom objetivo é investigável.</b><span>Evite objetivos amplos demais. O grupo precisa saber qual evidência responde à pergunta.</span></div><div><b>Uma boa referência é útil ao grupo.</b><span>Explique o que a fonte acrescenta e vincule-a ao objetivo correspondente.</span></div><div><b>Uma boa mediação devolve perguntas.</b><span>O professor ajuda a turma a pensar melhor sem ocupar o lugar da investigação.</span></div></div></section>

          <section className="pbl-content-section pbl-faq" id="duvidas"><SectionHeading number="?" eyebrow="Ajuda rápida" title="Dúvidas comuns" /><details><summary>O que faço se o professor ainda não liberou o cenário?</summary><p>Aguarde na sala e confira se você está na turma correta. O professor controla a liberação e o avanço dos passos para que todos comecem juntos.</p></details><details><summary>Quem pode editar o whiteboard?</summary><p>O Relator é o responsável por registrar no whiteboard, mas todos os participantes devem contribuir com hipóteses, correções e conexões pelo chat e pela conversa.</p></details><details><summary>Posso anexar uma referência a qualquer objetivo?</summary><p>Sim, quando a etapa estiver liberada. Escolha um objetivo e anexe uma fonte que realmente ajude a responder a pergunta daquele objetivo.</p></details><details><summary>Como sei se a sessão terminou?</summary><p>O professor finaliza o P7. A tela muda para o estado de encerramento e os registros ficam disponíveis para a ata, a avaliação e os relatórios.</p></details><details><summary>O que fazer se minha conexão cair?</summary><p>Retorne ao mesmo painel e à mesma sala. Não crie uma nova participação. Se necessário, avise o professor informando seu nome e a etapa em que estava.</p></details><details><summary>Onde encontro a documentação técnica?</summary><p>A documentação detalhada das ferramentas, papéis, integrações e configurações está disponível no menu Documentação, após entrar na plataforma.</p></details></section>

          <div className="pbl-end-note"><span aria-hidden="true">✦</span><p>Pronto. Agora você já sabe como preparar, entrar, participar, conduzir e encerrar uma sessão PBL no PBL Virtual.</p></div>
        </div>
      </div>
    </main>

    <footer className="pbl-footer"><div><b>PBL Virtual</b><span>Guia de uso da plataforma</span></div><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>Voltar ao início <ArrowUp className="inline h-3 w-3" /></button></footer>
  </div>;
}
